### ISSUE TITLE
works in firefox but not chrome?

### ISSUE THREAD

**Issue by pdbogen** [jrmycanady/nokiahealth#10]
This is a quite bizarre problem, I think.. The code is working well for me in firefox, but in chrome the oauth process fails at at the call to `(AccessRequest) GenerateUser`. The error passed up from the library is `oauth1: Response missing oauth_token or oauth_token_secret`.

Here's my code: https://github.com/pdbogen/vator

And specifically here's the call that's failing: https://github.com/pdbogen/vator/blob/master/oauth.go#L45

I'll keep digging, myself, but if you have any insight or ideas, I'd welcome some clues.

**Comment by jrmycanady** [comment]
Is it actually this line that is throwing the error?
https://github.com/pdbogen/vator/blob/master/oauth.go#L46

I also see you log the parameters upon failure. Do they all look valid when it fails?

**Comment by jrmycanady** [comment]
Closing as the Oauth1 API will be gone soon and v2 using Oauth2 will be the only usable version.
