### ISSUE TITLE
Run the go application 

### ISSUE THREAD

**Issue by elvincsci** [jrmycanady/nokiahealth#7]
I'm new to go and i'm looking to make API calls to Nokia to fetch weight data from Nokia scale. I installed using "go get github.com/jrmycanady/nokiahealth" tried running it and its not working. Any idea why ?

**Comment by jrmycanady** [comment]
When you say you tried to run it, what exactly are you trying to do? I ask because this is just a library so no executable will be generated.

**Comment by elvincsci** [comment]
I'm trying to get the userToken and the userSecret after using the NewClient method and obtaining the UserID and the verifier. See attachment 
<img width="797" alt="screen shot 2018-02-27 at 12 23 32 pm" src="https://user-images.githubusercontent.com/19851347/36747000-5cfb3af4-1bb9-11e8-844e-47ca5f977c3a.png">
