### ISSUE TITLE
Get lastUpdate 

### ISSUE THREAD

**Issue by ProgrammingFuad** [jrmycanady/nokiahealth#9]
Jeremy awesome library, I just had a few questions:
 
1. I'm getting an error message when trying to get the "LastUpdate", after setting the date to today or time.Now(). The specific Error message states:  "Panic: runtime error: invalid memory address or nil pointer deference. 
code : 
 
today := time.Now()
p := BodyMeasuresQueryParams{LastUpdate : &today}

The only time it works is when the time is set to "nil", in which case it returns all the weight data for the account.

2.  Is it possible to get the weight data (date, weight) in JSON {"data":"12/12/2012","weight":"77"} or get the original JSON results from Nokia ?

**Comment by jrmycanady** [comment]
Interesting. I will look into it here in a bit. 

Do you have a longer sample of the code and where it's throwing the panic?

**Comment by ProgrammingFuad** [comment]
I'm using the nokiahealth_test.go that you included, but I remove/replace startData and EndDate with LastUpdate. It's throwing the panic at "m, err := u.GetBodyMeasurement(&p)"
<img width="978" alt="screen shot 2018-03-07 at 12 53 46 pm" src="https://user-images.githubusercontent.com/8013859/37111958-c6897b5e-2206-11e8-9e9b-994559492313.png">

**Comment by pdbogen** [comment]
@ProgrammingFuad can you include the full backtrace from the panic? Your screenshot shows the test call and the panic call but cuts off the lines that would explain where the panic is coming from in the library code.

**Comment by pdbogen** [comment]
@ProgrammingFuad also, can you double check which SHA of the library you're using? This might actually be the issue I fixed in #6 .

**Comment by jrmycanady** [comment]
@ProgrammingFuad, I know it has been a while but did you ever make any progress on the panic? Fixing the library for Oauth2 and wanted to see if this was still valid.

Also, you can get the raw response from Nokia by setting the SaveRawResponse field of the client to true. Then on the response from all api calls will have a RawResponse field populated with the raw body returned by the API.

**Comment by jrmycanady** [comment]
Closing due to rebuild and no response.
